# Generated by Django 4.0.4 on 2023-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок на русском')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок на английском')),
                ('title_uzl', models.CharField(max_length=200, verbose_name='Заголовок на узбекском (лат)')),
                ('title_uzc', models.CharField(max_length=200, verbose_name='Заголовок на узбекском (кир)')),
                ('img', models.ImageField(upload_to='gardens/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сад',
                'verbose_name_plural': 'Сады',
            },
        ),
    ]
