# Generated by Django 4.0.4 on 2023-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_garden_slug_alter_garden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='cultivated_area',
            field=models.IntegerField(default=123, verbose_name='Культивируемая территория'),
            preserve_default=False,
        ),
    ]
