# Generated by Django 4.0.4 on 2023-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_garden_cultivated_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='text_en',
            field=models.TextField(default=123, verbose_name='Текст на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='text_ru',
            field=models.TextField(default=123, verbose_name='Текст на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='text_uzc',
            field=models.TextField(default=123, verbose_name='Текст на узбекском (кир)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='text_uzl',
            field=models.TextField(default=123, verbose_name='Текст на узбекском (лат)'),
            preserve_default=False,
        ),
    ]
