# Generated by Django 4.0.4 on 2023-01-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_garden_text_en_garden_text_ru_garden_text_uzc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год посадки')),
                ('nut', models.CharField(max_length=200, verbose_name='Вид ореха')),
                ('area', models.IntegerField(verbose_name='Территория')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growtimes', to='mainapp.garden', verbose_name='Сад')),
            ],
            options={
                'verbose_name': 'Время посадки',
                'verbose_name_plural': 'Время посадки',
            },
        ),
    ]
