# Generated by Django 4.0.4 on 2023-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_growtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growtime',
            name='nut',
        ),
        migrations.AddField(
            model_name='growtime',
            name='nut_en',
            field=models.CharField(default=123, max_length=200, verbose_name='Вид ореха на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growtime',
            name='nut_ru',
            field=models.CharField(default=123, max_length=200, verbose_name='Вид ореха на русскм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growtime',
            name='nut_uzc',
            field=models.CharField(default=123, max_length=200, verbose_name='Вид ореха на узбекском (кир)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growtime',
            name='nut_uzl',
            field=models.CharField(default=123, max_length=200, verbose_name='Вид ореха на узбекском (лат)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garden',
            name='cultivated_area',
            field=models.FloatField(verbose_name='Культивируемая территория'),
        ),
        migrations.AlterField(
            model_name='growtime',
            name='area',
            field=models.FloatField(verbose_name='Территория'),
        ),
    ]
