# Generated by Django 4.0.4 on 2023-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_growtime_nut_nutvariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='nut',
            name='nut_kind',
            field=models.CharField(choices=[('walnut', 'walnut'), ('almond', 'almond')], default=1, max_length=200, verbose_name='Вид ореха'),
            preserve_default=False,
        ),
    ]
