# Generated by Django 4.0.4 on 2023-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_nut_nut_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nut',
            name='nut_kind',
            field=models.CharField(choices=[('walnut', 'Грецкий орех'), ('almond', 'Миндаль')], max_length=200, verbose_name='Вид ореха'),
        ),
    ]
