# Generated by Django 4.0.4 on 2023-02-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_nut_nut_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nut',
            name='nut_kind',
        ),
    ]
