# Generated by Django 4.0.4 on 2023-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_nut_nut_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='nut_kind',
            field=models.CharField(choices=[('walnut', 'Грецкий орех'), ('almond', 'Миндаль')], default=1, max_length=200, verbose_name='Вид ореха'),
            preserve_default=False,
        ),
    ]
