# Generated by Django 3.1.4 on 2023-11-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20231127_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Краткое описание на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Краткое описание на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description_uzc',
            field=models.TextField(default=1, verbose_name='Краткое описание на узбекском (кир)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description_uzl',
            field=models.TextField(default=1, verbose_name='Краткое описание на узбекском (лат)'),
            preserve_default=False,
        ),
    ]
