# Generated by Django 3.1.4 on 2023-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20231129_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-08-23', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
