# Generated by Django 3.1.4 on 2023-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=1, upload_to='posts/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
