# Generated by Django 3.1.4 on 2023-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20231129_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя на английском')),
                ('name_uzl', models.CharField(max_length=200, verbose_name='Имя на узбекском (лат)')),
                ('name_uzc', models.CharField(max_length=200, verbose_name='Имя на узбекском (кир)')),
                ('speciality_ru', models.TextField(verbose_name='Специальность на русском')),
                ('speciality_en', models.TextField(verbose_name='Специальность на английском')),
                ('speciality_uzl', models.TextField(verbose_name='Специальность на узбекском (лат)')),
                ('speciality_uzc', models.TextField(verbose_name='Специальность на узбекском (кир)')),
                ('img', models.ImageField(upload_to='authors/', verbose_name='Фото (100x100)')),
            ],
        ),
    ]
