# Generated by Django 3.1.4 on 2023-11-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
