# Generated by Django 3.1.4 on 2023-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(default=1, verbose_name='Текст на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(default=1, verbose_name='Текст на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_uzc',
            field=models.TextField(default=1, verbose_name='Текст на узбекском (кир)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_uzl',
            field=models.TextField(default=1, verbose_name='Текст на узбекском (лат)'),
            preserve_default=False,
        ),
    ]
