# Generated by Django 3.1.4 on 2023-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20231202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='speciality_en',
            field=models.CharField(max_length=200, verbose_name='Специальность на английском'),
        ),
        migrations.AlterField(
            model_name='author',
            name='speciality_ru',
            field=models.CharField(max_length=200, verbose_name='Специальность на русском'),
        ),
        migrations.AlterField(
            model_name='author',
            name='speciality_uzc',
            field=models.CharField(max_length=200, verbose_name='Специальность на узбекском (кир)'),
        ),
        migrations.AlterField(
            model_name='author',
            name='speciality_uzl',
            field=models.CharField(max_length=200, verbose_name='Специальность на узбекском (лат)'),
        ),
    ]
