# Generated by Django 5.0.4 on 2024-05-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20231202_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название на английском')),
                ('name_uzl', models.CharField(max_length=200, verbose_name='Название на узбекском (лат)')),
                ('name_uzc', models.CharField(max_length=200, verbose_name='Название на узбекском (кир)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='growtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nut',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutvariety',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя на английском')),
                ('name_uzl', models.CharField(max_length=200, verbose_name='Имя на узбекском (лат)')),
                ('name_uzc', models.CharField(max_length=200, verbose_name='Имя на узбекском (кир)')),
                ('description_ru', models.TextField(verbose_name='Краткое описание на русском')),
                ('description_en', models.TextField(verbose_name='Краткое описание на английском')),
                ('description_uzl', models.TextField(verbose_name='Краткое описание на узбекском (лат)')),
                ('description_uzc', models.TextField(verbose_name='Краткое описание на узбекском (кир)')),
                ('text_ru', models.TextField(verbose_name='Текст на русском')),
                ('text_en', models.TextField(verbose_name='Текст на английском')),
                ('text_uzl', models.TextField(verbose_name='Текст на узбекском (лат)')),
                ('text_uzc', models.TextField(verbose_name='Текст на узбекском (кир)')),
                ('img', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
