# Generated by Django 5.1.6 on 2025-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_category_alter_author_id_alter_garden_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название на английском')),
                ('name_uzl', models.CharField(max_length=200, verbose_name='Название на узбекском (лат)')),
                ('name_uzc', models.CharField(max_length=200, verbose_name='Название на узбекском (кир)')),
                ('video', models.FileField(upload_to='videogallery/', verbose_name='Видео (MP4 или WEBM)')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеогаллерея',
            },
        ),
    ]
